name: ned_guide
description: "A Project About NED University"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/ned_logo.png
     

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Regular.ttf
        - asset: assets/fonts/Arimo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arimo-Italic.ttf
          style: italic
        - asset: assets/fonts/Arimo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Arimo-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Arimo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Arimo-MediumItalic.ttf
          weight: 500
          style: italic
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
